import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#00dce6",
        "surface": "#131313",
        "on-tertiary": "#520071",
        "surface-variant": "#353534",
        "primary-container": "#00f3ff",
        "secondary": "#ffb3b2",
        "on-primary": "#00373a",
        "surface-bright": "#3a3939",
        "inverse-on-surface": "#313030",
        "on-primary-container": "#006b71",
        "surface-container": "#201f1f",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#74009f",
        "tertiary-fixed-dim": "#ecb2ff",
        "background": "#131313",
        "on-tertiary-container": "#9c00d2",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#92001e",
        "primary-fixed": "#6ff6ff",
        "on-surface": "#e5e2e1",
        "primary": "#e3fdff",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed": "#410008",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#5b000f",
        "outline-variant": "#3a494b",
        "surface-container-low": "#1c1b1b",
        "on-secondary": "#680012",
        "tertiary-container": "#f5cfff",
        "on-surface-variant": "#b9cacb",
        "error-container": "#93000a",
        "tertiary": "#fff6fc",
        "surface-dim": "#131313",
        "outline": "#849495",
        "inverse-primary": "#00696f",
        "on-primary-fixed-variant": "#004f53",
        "surface-container-lowest": "#0e0e0e",
        "on-error": "#690005",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#f8d8ff",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b2",
        "on-tertiary-fixed": "#320047",
        "secondary-container": "#ff525c",
        "on-primary-fixed": "#002022",
        "surface-tint": "#00dce6"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-space-grotesk)"],
      },
    },
  },
  plugins: [],
};
export default config;
