import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#00dce6",
        "surface": "#131315",
        "secondary-fixed-dim": "#ffb3b2",
        "surface-container": "#201f21",
        "on-surface-variant": "#b9cacb",
        "surface-container-low": "#1c1b1d",
        "on-secondary-container": "#5b000f",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#74009f",
        "error": "#ffb4ab",
        "secondary-fixed": "#ffdad8",
        "primary": "#e3fdff",
        "on-secondary-fixed": "#410008",
        "on-primary-fixed": "#002022",
        "primary-container": "#00f3ff",
        "on-background": "#e5e1e4",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#92001e",
        "secondary": "#ffb3b2",
        "error-container": "#93000a",
        "outline": "#849495",
        "outline-variant": "#3a494b",
        "inverse-on-surface": "#313032",
        "surface-container-highest": "#353437",
        "on-primary-fixed-variant": "#004f53",
        "surface-variant": "#353437",
        "background": "#131315",
        "on-primary": "#00373a",
        "on-secondary": "#680012",
        "tertiary-fixed-dim": "#ecb2ff",
        "on-surface": "#e5e1e4",
        "secondary-container": "#ff525c",
        "inverse-surface": "#e5e1e4",
        "surface-bright": "#39393b",
        "tertiary-container": "#f5cfff",
        "primary-fixed": "#6ff6ff",
        "surface-tint": "#00dce6",
        "inverse-primary": "#00696f",
        "surface-container-high": "#2a2a2c",
        "surface-dim": "#131315",
        "on-tertiary-fixed": "#320047",
        "on-primary-container": "#006b71",
        "tertiary": "#fff6fc",
        "on-tertiary": "#520071",
        "on-tertiary-container": "#9c00d2",
        "surface-container-lowest": "#0e0e10",
        "tertiary-fixed": "#f8d8ff"
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-space-grotesk)"],
      },
    },
  },
  plugins: [],
};
export default config;
